In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('train.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data.drop('PassengerId', inplace=True, axis=1)

In [5]:
data.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [6]:
data.drop('Name', inplace=True, axis=1)

In [7]:
data.head()

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0         0       3    male  22.0      1      0         A/5 21171   7.2500   
1         1       1  female  38.0      1      0          PC 17599  71.2833   
2         1       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3         1       1  female  35.0      1      0            113803  53.1000   
4         0       3    male  35.0      0      0            373450   8.0500   

  Cabin Embarked  
0   NaN        S  
1   C85        C  
2   NaN        S  
3  C123        S  
4   NaN        S

In [8]:
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [9]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [10]:
data.isna().any()

Survived    False
Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Ticket      False
Fare        False
Cabin        True
Embarked     True
dtype: bool

In [11]:
data['Age'].isna().sum()

177

In [12]:
data['Age'].fillna(data['Age'].mean(), inplace=True)

In [13]:
data['Cabin'].isna().sum()

687

In [14]:
len(data)

891

In [15]:
data.drop('Cabin', inplace=True, axis=1)

In [16]:
data.head()

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0         0       3    male  22.0      1      0         A/5 21171   7.2500   
1         1       1  female  38.0      1      0          PC 17599  71.2833   
2         1       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3         1       1  female  35.0      1      0            113803  53.1000   
4         0       3    male  35.0      0      0            373450   8.0500   

  Embarked  
0        S  
1        C  
2        S  
3        S  
4        S

In [17]:
data['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [18]:
data['Embarked'].isna().sum()

2

In [19]:
data['Embarked'].fillna('S', inplace=True)

In [20]:
data['Embarked'].isna().sum()

0

In [21]:
data['SibSp'].value_counts()

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64

In [22]:
data['Parch'].value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64

In [23]:
data.drop(['SibSp','Parch','Ticket','Fare', 'Embarked'], inplace=True, axis=1)

In [24]:
data.head()

Survived  Pclass     Sex   Age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [25]:
gender_data = pd.DataFrame(data['Sex'])

In [26]:
encoded_data = pd.get_dummies(gender_data)

In [27]:
data.drop('Sex', inplace=True, axis=1)

In [28]:
encoded_data.head()

Sex_female  Sex_male
0           0         1
1           1         0
2           1         0
3           1         0
4           0         1

In [29]:
valid_data = pd.concat([data, encoded_data], axis=1)

In [30]:
valid_data.head()

Survived  Pclass   Age  Sex_female  Sex_male
0         0       3  22.0           0         1
1         1       1  38.0           1         0
2         1       3  26.0           1         0
3         1       1  35.0           1         0
4         0       3  35.0           0         1

In [31]:
y = valid_data[['Survived']]

In [32]:
y.head()

Survived
0         0
1         1
2         1
3         1
4         0

In [33]:
valid_data.drop('Survived', inplace=True, axis=1)

In [34]:
valid_data.head()

Pclass   Age  Sex_female  Sex_male
0       3  22.0           0         1
1       1  38.0           1         0
2       3  26.0           1         0
3       1  35.0           1         0
4       3  35.0           0         1

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(valid_data, y, test_size=0.2)

In [37]:
X_test.head()

Pclass   Age  Sex_female  Sex_male
58        2   5.0           1         0
91        3  20.0           0         1
435       1  14.0           1         0
307       1  17.0           1         0
399       2  28.0           1         0

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
model = GaussianNB()


In [40]:
model.fit(X_train, y_train)

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\naive_bayes.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [41]:
model.score(X_train, y_train)

0.7823033707865169

In [42]:
y_pred = model.predict(X_test)

In [43]:
model.classes_

array([0, 1], dtype=int64)

In [44]:
model.score(X_test, y_test)

0.8044692737430168

In [45]:
from sklearn.metrics import accuracy_score

In [46]:
accuracy_score(y_test, y_pred)

0.8044692737430168

In [47]:
data = X_test.iloc[9]

In [48]:
model.predict([data])

array([0], dtype=int64)

In [49]:
y_test.iloc[9]

Survived    0
Name: 349, dtype: int64

In [50]:
import pickle

In [51]:
pickle.dump(model, open("titanic.pkl", "wb"))

In [52]:
saved_model = pickle.load(open("titanic.pkl", "rb"))

In [53]:
saved_model.predict([data])

array([0], dtype=int64)

In [54]:
data

Pclass         3.0
Age           42.0
Sex_female     0.0
Sex_male       1.0
Name: 349, dtype: float64

In [55]:
z = [2.0, 18.0, 0.0, 1.0]

In [57]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(max_depth=3, random_state=0)
rf_clf.fit(X_train, y_train)

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [58]:
rf_clf.predict([data])

array([0], dtype=int64)

In [61]:
data.shape

(4,)

In [62]:
test = [4.0, 48.0, 0.0, 1.0]

In [64]:
type(data)

pandas.core.series.Series

In [70]:
ser_test = pd.Series(test, index=['Pclass', 'Age', 'Sex_female' , 'Sex_male'])

In [71]:
ser_test


Pclass         4.0
Age           48.0
Sex_female     0.0
Sex_male       1.0
dtype: float64

In [72]:
type(ser_test)

pandas.core.series.Series

In [74]:
X_test.iloc[25]

Pclass         3.0
Age           22.0
Sex_female     0.0
Sex_male       1.0
Name: 80, dtype: float64

In [75]:
X_train.iloc[25]

Pclass         3.000000
Age           29.699118
Sex_female     1.000000
Sex_male       0.000000
Name: 573, dtype: float64

In [76]:
ser_test

Pclass         4.0
Age           48.0
Sex_female     0.0
Sex_male       1.0
dtype: float64

In [81]:
rf_clf.predict([X_test.iloc[30]])

array([1], dtype=int64)

In [82]:
y_train.iloc[30
        ]

Survived    1
Name: 443, dtype: int64

In [85]:
y_pred = rf_clf.predict(X_test)

In [86]:
y_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0], dtype=int64)

In [87]:
from sklearn.metrics import accuracy_score

In [88]:
accuracy_score(y_test, y_pred)

0.8324022346368715

In [91]:
from sklearn.metrics import precision_score

In [92]:
precision_score(y_test, y_pred)

0.7692307692307693

In [ ]:
pickle.dump(rf_clf, open('random_forest_titanic.pkl', 'wb'))